.vscode/launch.json

add `${workspaceRoot}` to make outDir an relative path so that we can avoid some errors when debug this plugin locally.

add workspaceRoot in launch options

---

syntaxes/haskell.tmLanguage

This fixes bad comment highlighting in module export list and resolves issue #2.
I have also submitted a pull request to the original Textmate Haskell bundle.

Fix comments in module export list

---

package.json

Changes to package.json to enable Literate Haskell Grammar, fixing #7.
I've tested with some personal files (bird style)
And with a small piece of LaTex.

Wiring Literate Haskell grammar

---

CHANGELOG.md
package.json

This PR simply fixes an ENOENT error that gets thrown on extension activation caused by the package.json file still referencing the snippets file that was deleted on the previous update.

Remove empty reference to old snippets file

---

syntaxes/cabal.tmLanguage

Support for `-- line comments` and custom setup declarations like this
custom-setup
setup-depends:  base >= 4.7 && < 5
, Cabal
, directory
, filepath
, process

Comments and custom-setup section support in .cabal files

---

syntaxes/haskell.tmLanguage

Could you please update this for syntax highlighting of numeric literals?
This patch implemented Haskell/GHC's newly accepted proposal for numeric literals. (I'm author of the proposal.)
* https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0009-numeric-underscores.rst#new-syntax-this-proposal
I visually verified this patch with a test file.
* https://github.com/takenobu-hs/ghc/blob/squashed-numeric-underscores/testsuite/tests/parser/should_run/NumericUnderscores0.hs
If you need more speed than accuracy, I will send the following fast (but approximate) pattern match version instead.
* https://github.com/JustusAdam/language-haskell/compare/master...takenobu-hs:patch-numeric-literal-fast
Regards,
Takenobu

Update syntax for numeric literals

---

package.json
syntaxes/codeblock-haskell.json

Partly addresses #48 but does not close it (still need `lhs`, `cabal` support).

Support for Markdown code fence (haskell, hs)

---

package.json
syntaxes/codeblock-cabal.json
syntaxes/codeblock-literate-haskell.json

Closes #48.
In addition to #55, which added markdown code fence support for `hs` and `lhs`, this PR:
- adds support for Literate Haskell using `literate-haskell`, `lhaskell`, and `lhs`
- adds support for Cabal using `cabal`
- makes support stricter by adding word boundaries `\b` to the regex for matching languages
One thing this PR does _not_ do is add any language to the README advertising or documenting this support. I don't know that it's necessary – this is a naturally discoverable, even expected, feature. I leave it up to you to decide how or if you want to incorporate that.

Markdown support for literate haskell and cabal

---

package.json

VSC uses the first language in the aliases list to populate the languages list. This PR simply puts the capitalized `Cabal` first, so it appears in the correct alphabetical position in the languages list, among all the other capitalized languages.

make capitalized Cabal default over lowercase in lang list

---

syntaxes/haskell.tmLanguage

I don't know how robust these changes are, but they're producing the result I want in my current projects.
With this change, setting "meta.import" tokens to have a certain color makes the qualifiers match the import statements, which seems logical to me.
It should support qualified names in infix expressions, e.g. \`Module.foo\`, \`Module.Submodule.bar\`.
Sorry if I forgot some cases.

Detect qualified types and functions

---

package.json
syntaxes/haskell.tmLanguage
test/syntax-examples/backpack.hsig

This may be a hacky way to do it, but I just enabled `.hs` highlighting on `.hsig` files and made the `signature` keyword act the same as the `module` keyword. This is a bit leaky, so suggestions are appreciated, but IMO this isn't much of an issue.

Add highlighting for backpack signature files

---

package.json

For current version, when running commands like `stack build`, stack will generate a `stack.yaml.lock` file, which does not match any language association in VS Code.
This PR associates `stack.yaml.lock` with `yaml` language id.

Associate stack.yaml.lock with yaml language mode

---

CHANGELOG.md
syntaxes/cabal.tmLanguage

This PR updates the .cabal grammar to support `benchmark` components, `common` stanzas, and `import` & `autogen-modules` fields.

Cabal highlighting improvements

---

CHANGELOG.md
syntaxes/haskell.tmLanguage

This PR requires a word boundary following `::` for it to be recognized as the type signature operator. This fixes an issue where custom operators beginning with `::` were incorrectly being recognized as type signatures.

Type sig punctuation tokenization

---

literate-haskell-configuration.json
package.json

Implemented suggested fix for #24 
I think ideally the comments would be contextual (and perhaps configurable), but this change is a good start.

Change single line comments in lhs files to %.

---

CHANGELOG.md
package.json

This trivial change enables support for `hs-boot` files.    
I've looked at the results on the `hs-boot` files I have been working with, and the highlighting doesn't seem to run into any issues. Concerning the oddity
```haskell
type family ClosedFam a where ..
```
`..` uses the scope `keyword.operator.haskell`, which seems to work fine even if it perhaps isn't ideal.

Enable highlighting for hs-boot files (fixes #117)

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/syntax-examples/test.hs

This fixes issue #118.
I've also updated the test file to showcase the issue from #121, which I have **not** fixed.

Allow extra spaces between record field name and type signature (fixes #118)

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/syntax-examples/test.hs

This adds support for the `anyclass`, `stock` and `newtype` deriving strategies.
Also includes a minor bugfix: the extension didn't recognise a standalone derived instance if there were extra spaces, for instance:
```haskell
deriving    instance Eq D
```
That is now fixed.

Add support for deriving strategies (#72)

---

CHANGELOG.md
syntaxes/cabal.YAML-tmLanguage
test/syntax-examples/test.cabal

Adds support for `cabal` [internal libraries](https://www.haskell.org/cabal/users-guide/developing-packages.html#sublibs) and the associated [visibility](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-library-visibility) field.    
Also added `common` stanza to the `cabal` test-case to demonstrate commits c8342a8 and 6a77a9f.

Add support for cabal internal libraries

---

syntaxes/haskell.YAML-tmLanguage
test/syntax-examples/test.hs

The latest release changed from `keyword.other.double-colon` to `keyword.operator.double-colon` but one remaining use of `other` lingered.
I've also added back highlighting for `::` appearing inside type signatures, see test case:
```haskell
colons :: forall (a :: (k :: l)). a -> (x :: a) -> k
data X ( a :: ( x :: k ) ) :: k
```

Consistently highlight double colon

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tickets/T0072a.hs
test/tickets/T0072b.hs
test/tickets/T0072c.hs

The regular expression for `deriving via` insisted on the need for parentheses, but those aren't required.
I also removed the `entity.other.inherited-class.haskell` scope (which was seemingly only used for `deriving-via`) and replaced it with the `type_signature` TextMate pattern. This allows code like the following to render correctly:
```haskell
deriving via '(F A, B) instance R '(A, G B)
````
I've added that to the test file.
Demonstration:
before:
after:

Adjust highlighting for deriving via and instances

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tickets/T0070.hs
test/tickets/T0111.hs
test/tickets/T0136.hs

This fixes the issues outlined in ticket #136. I've also taken the liberty of changing `keyword.operator.custom.haskell` to `storage.type.operator.haskell`, as in my opinion symbolic operators should be treated much the same as ones that start with a letter.

Improve support for promotion ticks (fixes #136)

---

syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tickets/T0112.hs

As seen for instance [here](https://hackage.haskell.org/package/telegram-raw-api-0.1.0/docs/src/Web.Telegram.API.Lens.html), pragmas can be allowed within the module declaration header. So I've simply allowed pragmas to be parsed at that location. This fixes `T0112`.

Allow pragmas in module declaration headers

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tickets/T0020b.hs

This adds record syntax for GADTs, fixing test case `T0020b`:
```haskell
data A where
A :: { field1 :: Int, field2 :: Int } -> A
data B where
B
:: { field3 :: Bool
, field4 :: Int
}
-> B
```
(GitHub gets this wrong it seems.)

Support record syntax in GADTs

---

syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tests/Exports.hs
test/tests/Haddocks.hs
test/tests/MultiLineTypeSignatures.hs
test/tests/TypeSigs.hs
test/tickets/T0072b2.hs

Recognises the `type` keyword in module export lists, and adds some tests (one related, others not) that don't currently pass.

Add type keyword to module exports

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tickets/T0002.hs
test/tickets/T0131.hs

I think the issue was that `include: $self` wasn't parsed properly. Rewriting it slightly differently seems to have solved the issue. Regression test in `T0131` should ensure this stays fixed.

Address LiquidHaskell regression 

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tests/UnusualTypeApplications.hs
test/tickets/T0073.hs
test/tickets/T0073b.hs

Type application is now detected by: space, then `@`, then an expression of the following three forms:
- between `(`, `)`
- between `[`, `]`
- a sequence of allowed characters as defined by `[\p{Ll}_\p{Lu}\p{Lt}\p{Nd}'']`
I added some tricky situations to the test case to check that it's behaving as expected, but please add more cases if you can spot other issues/potential issues.
Note that we're doing better than GitHub on this one! 😄 
Fixes test case `T0073`.

Highlight visible kind application, fixes to visible type application

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/tests/CPP.hs

Allows C preprocessor instructions to appear in module exports.
Also highlights the whole line, instead of falling back to Haskell highlighting (which looked wonky at times).

Allow CPP in module exports

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tests/Arrows.hs
test/tests/Exports.hs
test/tests/Fields.hs
test/tests/Imports.hs
test/tests/Keywords.hs
test/tests/NearReserved.hs
test/tests/Ticks.hs
test/tests/Tuples.hs
test/tests/TypeSigs.hs
test/tests/TypeVsData.hs
test/tickets/T0028.hs
test/tickets/T0028b.hs
test/tickets/T0029.hs
test/tickets/T0039b.hs
test/tickets/T0069.hs
test/tickets/T0070.hs
test/tickets/T0131.hs
test/tickets/T0136.hs

- Improves support for highlighting reserved operators:
```haskell
a <- b
```
```haskell
a -> b
```
```haskell
a = b
```
```haskell
\ a -> b
```
```haskell
a -< b
```
```haskell
a -<< b
```
- Fixes a bug where we would look ahead for a reserved operator such as `<-` but would match on something like `<--`.  That's been added to the tests.
- Fixes issues with highlighting type signatures: now a double-colon properly starts off the `type-signature` matching. It's still not perfect, as it would be good if it kept going on multiple lines (keeping track of indentation), so that it would still highlight properly something like:
```haskell
foo
:: forall a b
.  C x
=> D a
=> E b
-> G
```
(barring the problems with the first line which can't really be addressed).
- Adds support for prefix data …

Improved highlighting for symbolic operators: reserved and unreserved

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/test.sh
test/tickets/T0044.hs
test/tickets/T0072b.hs
test/tickets/T0072b2.hs
test/tickets/T0151.hs

I've rewritten the support for `foreign import`/`foreign export` to be a bit more robust, especially to handle highlighting of type signatures when written over multiple lines.
A bit of complexity to do with highlighting optional `safe`/`unsafe`/`interruptible` keywords while not highlighting them when they are the name of the function instead (which is allowed).

Improvements to foreign import/export declarations

---

CHANGELOG.md
syntaxes/literateHaskell.YAML-tmLanguage
test/tickets/T0172.lhs

per https://gitlab.haskell.org/ghc/ghc/-/blob/master/utils/unlit/unlit.c#L203-228, ghc skips all leading whitespace before checking for `\begin{code}` but [apparently not `\end{code}`](https://gitlab.haskell.org/ghc/ghc/-/blob/master/utils/unlit/unlit.c#L271-282), so this is valid. there's a related [ghc issue](https://gitlab.haskell.org/ghc/ghc/-/issues/3549) from ten years ago but it looks like it's gone mostly ignored for a while.
not sure if existing test infrastructure can handle `.lhs` files, but it looks like it can't, so i'm not sure how i'd add a test.
(this is useful for me because i'm writing homework assignments as markdown-ish `.lhs` files and using pandoc to render out PDFs, but i need code blocks to be within lists or else everything turns out ugly.)

allow indentation on `\begin{code}`

---

CHANGELOG.md
package.json

VSCode seems to use the first extension listed in the list of extensions as the default extension for saving files.
Fixes #197

Default to .hs when saving Haskell files

---

CHANGELOG.md
syntaxes/haskell.YAML-tmLanguage
test/tests/QuasiQuotes.hs

Problem: currently parsing `[int||Text|]` fails with the current Haskell
grammar.
This happens, because we parse the beginning in a greedy way, and so
parse `[int||` as beginning of typed quasi-quoter. Thus end must be
`||]` respectively, but we never meet it.
Solution: custom quoters are never typed, and GHC (tried with 8.10.7
version) interprets `[int||Abc||]` as a mere quoter with `|Abc|` body.
So here we adjust the pattern for custom quoters to be never typed.
Resolves #203.

Improve custom quasi-quotation parsing

---

CHANGELOG.md
package.json

As far as I can see there is nothing preventing this extension from supporting untrusted namespaces.
The only reason is this is not done automatically by VS Code is because of the [main entry point](https://code.visualstudio.com/api/extension-guides/workspace-trust#does-my-extension-have-a-main-entry-point), but I don't think we do anything in `extension.ts` the could be exploited by a malicious workspace.

Add the untrustedWorkspaces capability

---

test/test.sh
test/tests/Keywords.hs

It seems this is no longer supported by `vscode-tmgrammar-test`? Let's see if CI passes with this change.

WIP: remove -s from tests

---

CHANGELOG.md
syntaxes/cabal.YAML-tmLanguage

Fix #201 Support elif in Cabal files
